spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wxfc?characterEncoding=utf8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

  # thymeleaf模板配置
  thymeleaf:
    cache: false    # 这个开发配置为false，避免改了模板还要重启服务器
    prefix: classpath:/templates/     # 这个是配置模板路径的，默认就是templates，可不用配置
    check-template-location: true     # 这个可以不配置，检查模板位置
    suffix: .html
    encoding: utf-8
    content-type: text/html
    mode: HTML5

logging:
#  path: /Users/everseeker/Log/wxfc
  path: /home/wxfc/log
  level:
    root: INFO
    org.springframework.web: INFO
