spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wxfc?characterEncoding=utf8&useSSL=false
    username: root
    password: 333
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  activemq:
    in-memory: true
    user: admin
    password: admin

logging:
  path: /Users/everseeker/Log/wxfc
  level:
    root: INFO
    org.springframework.web: DEBUG
